### ISSUE TITLE
A pax.chess project

### ISSUE THREAD

**Issue by aGrabson** [ipax77/pax.chess#1]
Hi I'd like to contact you, me and my friend are during school project. Do you have some documentation how to use chess engine that'll be compatible to it?

**Comment by ipax77** [comment]
Hey, you can find the related engine project [here](https://github.com/ipax77/pax.uciChessEngine). A (quite old) sample project using Blazor is [here](https://github.com/ipax77/pax.BlazorChess)

**Comment by aGrabson** [comment]
Engine engine = new Engine("EngineName", @"path\to\engine\binary"); 
What's the engine to be put in this path?

**Comment by ipax77** [comment]
What ever engine you want [(https://github.com/ipax77/pax.BlazorChess#prerequisites](https://github.com/ipax77/pax.BlazorChess#prerequisites)
