### ISSUE TITLE
State.ValidPositions returns illegal moves for pinned pieces

### ISSUE THREAD

**Issue by morganbr** [ipax77/pax.chess#2]
If moving a piece would reveal a check on its own king, ```Game.Move``` correctly rejects the move with ```MoveState.WouldBeCheck```, but it's included in the list of moves returned by ```State.ValidPositions``` for that piece.

**Comment by ipax77** [comment]
Works as designed
```
    /// <summary>
    /// Returns all technically possible moves for the given piece and state
    /// </summary>
    /// <remarks>
    /// <para>
    /// There is no check whether it would be check or checkmate 
    /// </para>
    /// </remarks>    
```   
Checking for check / -mate is very expensive and is skipped for this one. You can test the returned moves with `Validate.TryExecuteMove` (and `State.RevertMove` if successful)
