### ISSUE TITLE
Wrong Index in Fen.MapString infos[3]  EnPassantPosition Analyse

### ISSUE THREAD

**Issue by hajome73** [ipax77/pax.chess#3]
Hello,

i got errors if i used new Game() with FENs like 'rnbqkbnr/pp2pppp/3p4/2p5/8/1P3P2/P1PPP1PP/RNBQKBNR w KQkq c5 0 2' with  EnPassants.
and i found in Fen.MapString
https://github.com/ipax77/pax.chess/blob/5b2a8bb4efa03d25d705e123df3291aa47d543e3/src/pax.chess/Fen.cs#L39-L50

changing infos[2] into infos[3] and it's works as designed.

Best regards

**Comment by ipax77** [comment]
Fixed with version 0.6.2 - thank you for reporting!
